pipeline{
  agent {label 'ubuntu'}
  options { buildDiscarder(logRotator(numToKeepStr: '3'))}
  parameters {
    choice(choices: ['GSDEV', 'GSUAT', 'GSPRD'], name:'env', description: 'Environment to deploy')
    choice(choices: ['us-east-2', 'us-east-1'], name: 'region')
    gitParameter(
      branchFilter: 'origin/(.*)',
      defaultValue: 'master',
      name: 'BRANCH',
      type: 'PT_BRANCH'
    )
  }
  stages{
    stage('Prepare'){
      steps{
        script{
          currentBuild.displayName = "${params.env}"-"${params.BRANCH}-${BUILD_NUMBER}"
          echo "CurrentUser: $env.BUILD_USER_ID"
        }
      }
    }
    stage('Say Hello!'){
      steps{
        script {
          echo "Hello, Friend, this is mr robot"
        }
      }
    }
    stage('Print the parameters'){
      steps{
        script{
          echo "The environment is: ${params.env}"
          echo "The region is: ${params.region}"
          echo "The BRANCH is: ${params.BRANCH}"
        }
      }
    }
  }
}
