pipeline{
  agent {label 'ubuntu'}
  options { buildDiscarder(logRotator(numToKeepStr: '3'))}
  stages{
    stage('Say Hello!'){
      steps{
        script {
          echo "Hello, Friend from the last and fifth api from this test"
        }
      }
    }
  }
}
