pipeline{
  agent any
  options { buildDiscarder(logRotator(numToKeepStr: '3'))}
  stages{
    stage('Say Hello!'){
      steps{
        script {
          echo "Hello, Friend from the fourth api"
        }
      }
    }
  }
}
